name: VansRenting
options:
  bundleIdPrefix: cz.vanscentre
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.0
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: 1
targets:
  VansRenting:
    type: application
    platform: iOS
    sources:
      - path: CrocodilleFleet
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_NAME: VansRenting
        PRODUCT_BUNDLE_IDENTIFIER: cz.vanscentre.vansrenting
        INFOPLIST_FILE: CrocodilleFleet/Info.plist
        GENERATE_INFOPLIST_FILE: NO
    scheme:
      testTargets: []
